spring.datasource.url=jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.schema-locations=classpath:schema.sql
db-scheduler.polling-interval=1s
db-scheduler-console.history.retention=7d
